apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: foo2
  janus-idp.io/tekton: foo2
  backstage.io/kubernetes-id: foo2
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: foo2
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
